# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1

jobs:
  build-api:
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build API
          command: npm run build-api
  build-ui:
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build UI
          command: npm run build-ui
  test:
    docker:
        - image: circleci/node:14.17
    steps:
      - checkout
      - node/install-packages
    - run:
        name: Run api tests
        command: npm run test-api
    - run:
        name: Run ui tests
        command: npm run test-ui
  lint:
    docker:
        - image: circleci/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
        name: Lint
        command: npm run lint
workflows:
  sample:
    jobs:
      - test
      - lint
      - build-ui
      - build-api